- name: Deploy Web Application
  hosts: agent1
  become: yes
  tasks:
    - name: install all required dependencies
      apt: name={{ item }} state=latest
      with_items: 
        - python3
        - python3-setuptools 
        - python3-dev 
        - build-essential 
        - python3-pip 
        - python3-mysqldb
        - python3-venv

    - name: Install mysql DataBase
      apt: name={{ item }} state=present
      with_items:
        - mysql-server
        - mysql-client

    - name: start mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: create application database
      mysql_db: name=employee_db state=present

    - name: Create Database user
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'

    - name: Install Python flask dependencies
      pip:
        name: "{{ item }}"
        executable: pip3
        state: present
      loop:
        - flask
        - flask-mysql

    - name: Copy source code
      copy: src=app.py dest=/opt/app.py

    - name: start wev server
      shell: FlASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 
